path.data <- "../data/"
path.data.raw <- paste0(path.data, "raw/")
path.data.proc <- paste0(path.data, "processed/")
file.survey.raw <- paste0(path.data.raw, "results-survey845375_clean.csv")
file.variables <- paste0(path.data.raw, "variables.csv")
file.variables.proc <- paste0(path.data.proc, "variables.rds")
file.variables.proc.csv <- paste0(path.data.proc, "variables.csv")
file.cat.levels.proc <- paste0(path.data.proc, "cat.levels.rds")
file.cat.levels.proc.csv <- paste0(path.data.proc, "cat.levels.csv")
file.questions <- paste0(path.data.proc, "questions.rds")
file.questions.dependencies <- paste0(path.data.proc, "questions.dependencies.rds")
file.survey.proc <- paste0(path.data.proc, "survey.rds")
file.survey.fit <- paste0(path.data.proc, "survey.fit.rds")
file.survey.n <- paste0(path.data.proc, "survey.n.rds")

path.results.w <- "../results/willingness/"
path.results.w.varsel <- paste0(path.results.w, "varsel/")
path.results.w.irt <- paste0(path.results.w, "irt/")
path.irt.w.plots <- paste0(path.results.w, "/plots/irt/")
file.survey.fit.w <- paste0(path.data.proc, "survey.fit.w.rds")
file.survey.irt.w <- paste0(path.data.proc, "survey.irt.w.rds")
file.mod.sel.w.prefix <- paste0(path.results.w.varsel, "mod.sel.")
file.var.sel.w.prefix <- paste0(path.results.w.varsel, "var.sel.")
file.var.sel.w.res <- paste0(path.results.w.varsel, "var.sel.res.rds")
file.var.sel.w.res.csv <- paste0(path.results.w.varsel, "var.sel.res.csv")
file.var.sel.w.plot <- paste0(path.results.w, "plots/varsel/var.sel.pdf")
file.irt.w.mod.2pl <- paste0(path.results.w.irt, "mod.2pl.rds")
file.irt.w.mod.2pl.nl <- paste0(path.results.w.irt, "mod.2pl.nl.rds")

path.results.u <- "../results/urgency/"
path.results.u.varsel <- paste0(path.results.u, "varsel/")
path.results.u.irt <- paste0(path.results.u, "irt/")
path.irt.u.plots <- paste0(path.results.u, "/plots/irt/")
file.survey.fit.u <- paste0(path.data.proc, "survey.fit.u.rds")
file.survey.irt.u <- paste0(path.data.proc, "survey.irt.u.rds")
file.mod.sel.u.prefix <- paste0(path.results.u.varsel, "mod.sel.")
file.var.sel.u.prefix <- paste0(path.results.u.varsel, "var.sel.")
file.var.sel.u.res <- paste0(path.results.u.varsel, "var.sel.res.rds")
file.var.sel.u.res.csv <- paste0(path.results.u.varsel, "var.sel.res.csv")
file.var.sel.u.plot <- paste0(path.results.u, "plots/varsel/var.sel.pdf")
file.irt.u.mod.2pl <- paste0(path.results.u.irt, "mod.2pl.rds")
file.irt.u.mod.2pl.nl <- paste0(path.results.u.irt, "mod.2pl.nl.rds")
