path.data <- "../data/"
path.data.raw <- paste0(path.data, "raw/")
path.data.proc <- paste0(path.data, "processed/")
file.survey.raw <- paste0(path.data.raw, "results-survey845375_clean.csv")
file.variables <- paste0(path.data.raw, "variables.csv")
file.variables.proc <- paste0(path.data.proc, "variables.rds")
file.variables.proc.csv <- paste0(path.data.proc, "variables.csv")
file.cat.levels.proc <- paste0(path.data.proc, "cat.levels.rds")
file.cat.levels.proc.csv <- paste0(path.data.proc, "cat.levels.csv")
file.questions <- paste0(path.data.proc, "questions.rds")
file.questions.dependencies <- paste0(path.data.proc, "questions.dependencies.rds")
file.survey.proc <- paste0(path.data.proc, "survey.rds")
file.survey.fit <- paste0(path.data.proc, "survey.fit.rds")
file.survey.n <- paste0(path.data.proc, "survey.n.rds")

path.results.w <- "../results/willingness/"
path.results.w.varsel <- paste0(path.results.w, "varsel/")
path.results.w.irt <- paste0(path.results.w, "irt/")
path.irt.w.plots <- paste0(path.results.w, "plots/irt/")
file.survey.fit.w <- paste0(path.data.proc, "survey.fit.w.rds")
file.survey.irt.w <- paste0(path.data.proc, "survey.irt.w.rds")
file.mod.sel.w.prefix <- paste0(path.results.w.varsel, "mod.sel.")
file.var.sel.w.prefix <- paste0(path.results.w.varsel, "var.sel.")
file.var.sel.w.res <- paste0(path.results.w.varsel, "var.sel.res.rds")
file.var.sel.w.res.csv <- paste0(path.results.w.varsel, "var.sel.csv")
file.var.sel.w.plot <- paste0(path.results.w, "plots/varsel/var.sel.pdf")
file.irt.w.mod.2pl <- paste0(path.results.w.irt, "mod.2pl.rds")
file.irt.w.mod.2pl.nl <- paste0(path.results.w.irt, "mod.2pl.nl.rds")
# For adaptation related to fire
file.survey.irt.w.fire <- paste0(path.data.proc, "survey.irt.w.fire.rds")
file.var.sel.w.res.fire <- paste0(path.results.w.varsel, "var.sel.res.fire.rds")
file.var.sel.w.res.fire.csv <- paste0(path.results.w.varsel, "var.sel.fire.csv")
file.var.sel.w.plot.fire <- paste0(path.results.w, "plots/varsel/var.sel.fire.pdf")
file.irt.w.mod.2pl.fire <- paste0(path.results.w.irt, "mod.2pl.fire.rds")
file.irt.w.mod.2pl.nl.fire <- paste0(path.results.w.irt, "mod.2pl.nl.fire.rds")

path.results.wo <- "../results/willingness.ord/"
path.results.wo.varsel <- paste0(path.results.wo, "varsel/")
path.results.wo.irt <- paste0(path.results.wo, "irt/")
path.irt.wo.plots <- paste0(path.results.wo, "plots/irt/")
file.survey.fit.wo <- paste0(path.data.proc, "survey.fit.wo.rds")
file.survey.irt.wo <- paste0(path.data.proc, "survey.irt.wo.rds")
file.mod.sel.wo.prefix <- paste0(path.results.wo.varsel, "mod.sel.")
file.var.sel.wo.prefix <- paste0(path.results.wo.varsel, "var.sel.")
file.var.sel.wo.res <- paste0(path.results.wo.varsel, "var.sel.res.rds")
file.var.sel.wo.res.csv <- paste0(path.results.wo.varsel, "var.sel.csv")
file.var.sel.wo.plot <- paste0(path.results.wo, "plots/varsel/var.sel.pdf")
file.irt.wo.mod.2pl <- paste0(path.results.wo.irt, "mod.2pl.rds")
file.irt.wo.mod.2pl.nl <- paste0(path.results.wo.irt, "mod.2pl.nl.rds")

path.results.ws <- "../results/willingness.sd/"
path.results.ws.varsel <- paste0(path.results.ws, "varsel/")
path.results.ws.irt <- paste0(path.results.ws, "irt/")
path.irt.ws.plots <- paste0(path.results.ws, "plots/irt/")
file.survey.fit.ws <- paste0(path.data.proc, "survey.fit.ws.rds")
file.survey.irt.ws <- paste0(path.data.proc, "survey.irt.ws.rds")
file.mod.sel.ws.prefix <- paste0(path.results.ws.varsel, "mod.sel.")
file.var.sel.ws.prefix <- paste0(path.results.ws.varsel, "var.sel.")
file.var.sel.ws.res <- paste0(path.results.ws.varsel, "var.sel.res.rds")
file.var.sel.ws.res.csv <- paste0(path.results.ws.varsel, "var.sel.csv")
file.var.sel.ws.plot <- paste0(path.results.ws, "plots/varsel/var.sel.pdf")
file.irt.ws.mod.2pl <- paste0(path.results.ws.irt, "mod.2pl.rds")
file.irt.ws.mod.2pl.nl <- paste0(path.results.ws.irt, "mod.2pl.nl.rds")

path.results.u <- "../results/urgency/"
path.results.u.varsel <- paste0(path.results.u, "varsel/")
path.results.u.irt <- paste0(path.results.u, "irt/")
path.irt.u.plots <- paste0(path.results.u, "plots/irt/")
file.survey.fit.u <- paste0(path.data.proc, "survey.fit.u.rds")
file.survey.irt.u <- paste0(path.data.proc, "survey.irt.u.rds")
file.mod.sel.u.prefix <- paste0(path.results.u.varsel, "mod.sel.")
file.var.sel.u.prefix <- paste0(path.results.u.varsel, "var.sel.")
file.var.sel.u.res <- paste0(path.results.u.varsel, "var.sel.res.rds")
file.var.sel.u.res.csv <- paste0(path.results.u.varsel, "var.sel.csv")
file.var.sel.u.plot <- paste0(path.results.u, "plots/varsel/var.sel.pdf")
file.irt.u.mod.2pl <- paste0(path.results.u.irt, "mod.2pl.rds")
file.irt.u.mod.2pl.nl <- paste0(path.results.u.irt, "mod.2pl.nl.rds")

path.results.c <- "../results/categorical/"
path.results.c.varsel <- paste0(path.results.c, "varsel/")
path.results.c.irt <- paste0(path.results.c, "irt/")
path.irt.c.plots <- paste0(path.results.c, "plots/irt/")
file.survey.fit.c <- paste0(path.data.proc, "survey.fit.c.rds")
file.survey.irt.c <- paste0(path.data.proc, "survey.irt.c.rds")
file.mod.sel.c.prefix <- paste0(path.results.c.varsel, "mod.sel.")
file.var.sel.c.prefix <- paste0(path.results.c.varsel, "var.sel.")
file.var.sel.c.res <- paste0(path.results.c.varsel, "var.sel.res.rds")
file.var.sel.c.res.csv <- paste0(path.results.c.varsel, "var.sel.csv")
file.var.sel.c.plot <- paste0(path.results.c, "plots/varsel/var.sel.pdf")
file.irt.c.mod.2pl <- paste0(path.results.c.irt, "mod.2pl.rds")
file.irt.c.mod.2pl.nl <- paste0(path.results.c.irt, "mod.2pl.nl.rds")

path.results.cs <- "../results/categorical.sd/"
path.results.cs.varsel <- paste0(path.results.cs, "varsel/")
path.results.cs.irt <- paste0(path.results.cs, "irt/")
path.irt.cs.plots <- paste0(path.results.cs, "plots/irt/")
file.survey.fit.cs <- paste0(path.data.proc, "survey.fit.cs.rds")
file.survey.irt.cs <- paste0(path.data.proc, "survey.irt.cs.rds")
file.mod.sel.cs.prefix <- paste0(path.results.cs.varsel, "mod.sel.")
file.var.sel.cs.prefix <- paste0(path.results.cs.varsel, "var.sel.")
file.var.sel.cs.res <- paste0(path.results.cs.varsel, "var.sel.res.rds")
file.var.sel.cs.res.csv <- paste0(path.results.cs.varsel, "var.sel.csv")
file.var.sel.cs.plot <- paste0(path.results.cs, "plots/varsel/var.sel.pdf")
file.irt.cs.mod.2pl <- paste0(path.results.cs.irt, "mod.2pl.rds")
file.irt.cs.mod.2pl.nl <- paste0(path.results.cs.irt, "mod.2pl.nl.rds")

